[profile.default]
src = "contracts"
out = "artifacts"
libs = ["node_modules", "lib"]
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat/=node_modules/hardhat/",
    "forge-std/=lib/forge-std/src/",
]

# RPC URLs for Polygon
[rpc_endpoints]
polygon_amoy = "https://polygon-amoy.g.alchemy.com/v2/wDbF6Bg_Z8DIHgyiz6x0zcIA09U-jZAB"
polygon = "https://polygon-mainnet.g.alchemy.com/v2/YOUR_ALCHEMY_API_KEY"

# PolygonScan API keys for verification
[etherscan]
polygon_amoy = { key = "YOUR_POLYGONSCAN_API_KEY", url = "https://api-testnet.polygonscan.com/api" }
polygon = { key = "YOUR_POLYGONSCAN_API_KEY", url = "https://api.polygonscan.com/api" }
